Exclude nightly features on stable rust
Using clear_on_drop on stable rust results in the following error:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/lib.rs:2:34
  |
2 | #![cfg_attr(feature = "nightly", feature(llvm_asm, i128_type, specialization))]
  |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: the feature `i128_type` has been stable since 1.26.0 and no longer requires an attribute to enable
```

This PR uses an additional `nightly` predicate to prevent this error on
stable rust